start python  C:\GIT\fala\ripley\ripley.py 0
start python  C:\GIT\fala\ripley\ripley.py 1
start python  C:\GIT\fala\ripley\ripley.py 2
start python  C:\GIT\fala\ripley\ripley.py 3
start python  C:\GIT\fala\ripley\ripley.py 4
start python  C:\GIT\fala\ripley\ripley.py 5
start python  C:\GIT\fala\ripley\ripley.py 6
start python  C:\GIT\fala\ripley\ripley.py 7
start python  C:\GIT\fala\ripley\ripley.py 8
start python  C:\GIT\fala\ripley\ripley.py 9
start python  C:\GIT\fala\ripley\ripley.py 10
start python  C:\GIT\fala\ripley\ripley.py 11
start python  C:\GIT\fala\ripley\ripley.py 12
start python  C:\GIT\fala\ripley\ripley.py 13
start python  C:\GIT\fala\ripley\ripley.py 14