start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley0.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley1.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley2.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley3.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley4.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley5.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley6.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley7.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley8.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley9.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley10.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley11.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley12.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley13.txt
start python  C:\GIT\fala\ripley\ripley.py C:\Git\fala\ripley\urls\test\ripley14.txt